.TH BUILD_TRN 1 2026-6月 "" "build_trn"
.SH NAME
build_trn \- build_trn(sites, diamond, link.code)
.SH SYNOPSIS
\fIbuild_trn(sites, diamond, link.code)\fR
.SH OPTIONS
.PP
\fBsites\fB \fR\- . 
.PP
.PP
\fBdiamond\fB \fR\- . 
.PP
.PP
\fBlink.code\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.build_trn at build_trn.R:line 2
.PP
.SH COPYRIGHT
Copyright © , MIT Licensed 2026
