.TH LOAD_TAXONOMY_LINKS 1 2026-6月 "" "load_taxonomy_links"
.SH NAME
load_taxonomy_links \- load_taxonomy_links(code,
    <i>data.frame</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIload_taxonomy_links(code,
    <i>data.frame</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBcode\fB \fR\- . 
.PP
.PP
\fBdata.frame\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_taxonomy_links at motif_links.R:line 22
.PP
.SH COPYRIGHT
Copyright © , MIT Licensed 2026
