.TH LOAD_GLOBAL_LINKS 1 2026-6月 "" "load_global_links"
.SH NAME
load_global_links \- load_global_links(
    <i>data.frame</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIload_global_links(
    <i>data.frame</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBdata.frame\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.load_global_links at motif_links.R:line 11
.PP
.SH COPYRIGHT
Copyright © , MIT Licensed 2026
