.TH LOCATE_MEME_DIR 1 2026-3月 "" "locate_meme_dir"
.SH NAME
locate_meme_dir \- locate_meme_dir(code)
.SH SYNOPSIS
\fIlocate_meme_dir(code)\fR
.SH OPTIONS
.PP
\fBcode\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.locate_meme_dir at motif_db.R:line 15
.PP
.SH COPYRIGHT
Copyright © , MIT Licensed 2026
