.TH MOTIF_TFSEQ 1 2026-3月 "" "Load internal TF sequence dataset"
.SH NAME
motif_tfseq \- motif_tfseq(code)
.SH SYNOPSIS
\fImotif_tfseq(code)\fR
.SH OPTIONS
.PP
\fBcode\fB \fR\- . 
.PP
.SH VALUE
.PP
a fasta sequence collection.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.motif_tfseq at motif_tfinfo.R:line 11
.PP
.SH COPYRIGHT
Copyright © , MIT Licensed 2026
