.TH PLANT_MOTIF_SEARCH 1 2026-6月 "" "plant_motif_search"
.SH NAME
plant_motif_search \- plant_motif_search(seqfile, plant.code,
    <i>outdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>)
.SH SYNOPSIS
\fIplant_motif_search(seqfile, plant.code,
    <i>outdir</i> = <span style='color: brown;'><strong>'./'</strong></span>,
    <i>n.threads</i> = <span style='color: green;'>8</span>)\fR
.SH OPTIONS
.PP
\fBseqfile\fB \fR\- . 
.PP
.PP
\fBplant.code\fB \fR\- . 
.PP
.PP
\fBoutdir\fB \fR\- './'. 
.PP
.PP
\fBn.threads\fB \fR\- 8. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.plant_motif_search at motif_search.R:line 1
.PP
.SH COPYRIGHT
Copyright © , MIT Licensed 2026
