.\" man page create by R# package system.
.TH TRN_TOOLS 1 2000-1月 "assign_classdata" "assign_classdata"
.SH NAME
assign_classdata \- assign the class information to the ORF inside TRN network
.SH SYNOPSIS
\fIassign_classdata(\fBregs\fR as any, 
\fBkb\fR as <generic> ClassClusterData[], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
assign the class information to the ORF inside TRN network
.PP
.SH OPTIONS
.PP
\fBregs\fB \fR\- the TRN network data. 
.PP
.PP
\fBkb\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
TRN_tools
.SH FILES
.PP
Plantea.dll
.PP
