.\" man page create by R# package system.
.TH TRN_TOOLS 1 2000-1月 "read_regulation" "read_regulation"
.SH NAME
read_regulation \- read regulation network from a given csv table file
.SH SYNOPSIS
\fIread_regulation(\fBfile\fR as string, 
\fBtqdm\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
read regulation network from a given csv table file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
TRN_tools
.SH FILES
.PP
Plantea.dll
.PP
