.\" man page create by R# package system.
.TH TRN_TOOLS 1 2000-1月 "term_subnetwork" "term_subnetwork"
.SH NAME
term_subnetwork \- create subnetwork by matches a set of terms
.SH SYNOPSIS
\fIterm_subnetwork(\fBregulations\fR as any, 
\fBterms\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create subnetwork by matches a set of terms
.PP
.SH OPTIONS
.PP
\fBregulations\fB \fR\- -. 
.PP
.PP
\fBterms\fB \fR\- bbh hit map data. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
TRN_tools
.SH FILES
.PP
Plantea.dll
.PP
