.\" man page create by R# package system.
.TH PLANTEA 1 2000-1月 "as.motif_links" "as.motif_links"
.SH NAME
as.motif_links \- create clr model for link the reference TF and the reference motif site model
.SH SYNOPSIS
\fIas.motif_links(\fBmatrix_id\fR as any, 
\fBtf_id\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create clr model for link the reference TF and the reference motif site model
.PP
.SH OPTIONS
.PP
\fBmatrix_id\fB \fR\- the motif id. 
.PP
.PP
\fBtf_id\fB \fR\- the transcript factor id. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Plantea
.SH FILES
.PP
Plantea.dll
.PP
