.\" man page create by R# package system.
.TH PLANTEA 1 2000-Jan "assign_classdata" "assign_classdata"
.SH NAME
assign_classdata \- 
.SH SYNOPSIS
\fIassign_classdata(\fBregs\fR as any, 
\fBkb\fR as <generic> ClassClusterData[], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Plantea
.SH FILES
.PP
Plantea.dll
.PP
