.\" man page create by R# package system.
.TH PLANTEA 1 2000-Jan "assign_tffamily" "assign_tffamily"
.SH NAME
assign_tffamily \- 
.SH SYNOPSIS
\fIassign_tffamily(\fBblastp\fR as any, 
\fBTFdb\fR as <generic> TFInfo[] = \fB<NULL>\fR, 
\fBtop_best\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Plantea
.SH FILES
.PP
Plantea.dll
.PP
