.\" man page create by R# package system.
.TH PLANTEA 1 2000-1月 "class_background" "class_background"
.SH NAME
class_background \- convert the gene cluster information as gsea background model
.SH SYNOPSIS
\fIclass_background(\fBgeneset\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
convert the gene cluster information as gsea background model
.PP
.SH OPTIONS
.PP
\fBgeneset\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Plantea
.SH FILES
.PP
Plantea.dll
.PP
