.\" man page create by R# package system.
.TH PLANTEA 1 2000-Jan "extract_tf_info" "extract_tf_info"
.SH NAME
extract_tf_info \- A helper function extract fo the PlantTFDB information
.SH SYNOPSIS
\fIextract_tf_info(\fBTF_fsa\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
A helper function extract fo the PlantTFDB information
.PP
.SH OPTIONS
.PP
\fBTF_fsa\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Plantea
.SH FILES
.PP
Plantea.dll
.PP
