.\" man page create by R# package system.
.TH PLANTEA 1 2000-Jan "load_motifdb" "load_motifdb"
.SH NAME
load_motifdb \- load motif database from a given xml list dataset
.SH SYNOPSIS
\fIload_motifdb(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
load motif database from a given xml list dataset
.PP
.SH SEE ALSO
Plantea
.SH FILES
.PP
Plantea.dll
.PP
