.\" man page create by R# package system.
.TH PLANTEA 1 2000-1月 "load_class" "load_class"
.SH NAME
load_class \- read the json list of csv table of the gene cluster data information
.SH SYNOPSIS
\fIload_class(\fBx\fR as string);\fR
.SH DESCRIPTION
.PP
read the json list of csv table of the gene cluster data information
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
Plantea
.SH FILES
.PP
Plantea.dll
.PP
