.\" man page create by R# package system.
.TH PLANTEA 1 2000-Jan "tf_network" "tf_network"
.SH NAME
tf_network \- 
.SH SYNOPSIS
\fItf_network(\fBmotifLinks\fR as <generic> MotifLink[], 
\fBmotif_hits\fR as <generic> MotifMatch[], 
\fBregulators\fR as any, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBmotifLinks\fB \fR\- -. 
.PP
.PP
\fBmotif_hits\fB \fR\- -. 
.PP
.PP
\fBregulators\fB \fR\- 
 should be a blast alignment result of the subclass of @\fBT:SMRUCC.genomics.ComponentModel.Annotation.IQueryHits\fR.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Plantea
.SH FILES
.PP
Plantea.dll
.PP
